platform: EKS

agent:
  requests:
    cpu: "500m"
    memory: "512Mi"
  annotations: {}

jobs:
  requests:
    cpu: "500m"
    memory: "512Mi"
  limits: {}
  annotations: {}

gpu:
  min_driver_version: "535.0"

thresholds:
  tcp_bandwidth_gbps:
    pass: 25
    warn: 10
    fail: 5
  rdma_bandwidth_pd_gbps:
    pass: 180
    warn: 100
    fail: 50
  rdma_bandwidth_wep_gbps:
    pass: 350
    warn: 200
    fail: 100
